name: Build

on:
  workflow_dispatch:
    branches:
        - '**'

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 25
      uses: actions/setup-java@main
      with:
        java-version: 25-ea
        distribution: temurin
    - name: Set-up NDK
      run: |
        yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses
        ./gradlew --warning-mode 'all' --no-daemon clean
    - name: Install Pino
      run: |
        declare -r PINO_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Pino/releases/latest')")"
        declare -r PINO_TARBALL='/tmp/toolchain.tar.xz'
        declare -r PINO_URL="https://github.com/AmanoTeam/Pino/releases/download/${PINO_TAG}/x86_64-unknown-linux-gnu.tar.xz"
            
        curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${PINO_URL}" --output "${PINO_TARBALL}"
        tar --directory="$(dirname "${PINO_TARBALL}")" --extract --file="${PINO_TARBALL}"
        
        echo '/tmp/pino/bin' >> "${GITHUB_PATH}"
    - name: Patch the NDK
      run: |
        ndk-patch
    - name: Build Android project
      env: 
        PINO_LTO: full
      run: |
        ./gradlew --warning-mode 'all' --no-daemon 'assembleRelease'
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk
